spring:
  datasource:
    url: jdbc:mysql://sh-cdb-dd5fr2w4.sql.tencentcdb.com:63654/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456aA@
  jackson:
    default-property-inclusion: non_null
  main:
    allow-circular-references: true
urule:
  repository:
    databasetype: mysql
    datasourcename: datasource

server:
  port: 8787
